name: publish to skynet
on:
  pull_request:
  push:
    branches: [master]

jobs:
  publish:
    name: build and publish to skynet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Build with dotnet
        run: dotnet build SiaSkynet.sln --configuration Release
      - name: Publish Website
        run: dotnet publish SiaSkynet.Sample.Blazor -o publish/SiaSkynet.Sample.Blazor -c Release
      - name: Deploy to Skynet
        uses: SkynetLabs/deploy-to-skynet-action@v2
        with:
          upload-dir: publish/SiaSkynet.Sample.Blazor/wwwroot
          github-token: ${{ secrets.GITHUB_TOKEN }}